# Generated by Django 4.2.30 on 2026-04-11 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('internet-mahazyny', 'Інтернет-магазини'), ('lendinhy', 'Лендінги'), ('korporatyvni-saity', 'Корпоративні сайти')], unique=True, verbose_name='Slug')),
                ('h1', models.CharField(max_length=200, verbose_name='H1 заголовок')),
                ('hero_subtitle', models.TextField(verbose_name='Підзаголовок hero')),
                ('meta_title', models.CharField(max_length=70, verbose_name='Meta title')),
                ('meta_description', models.CharField(max_length=160, verbose_name='Meta description')),
                ('price_from', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Ціна від')),
                ('price_currency', models.CharField(default='$', max_length=5, verbose_name='Валюта')),
                ('body_intro', models.TextField(blank=True, verbose_name='Вступний текст')),
                ('process_steps', models.JSONField(blank=True, default=list, help_text='JSON: [{"title": "...", "text": "..."}]', verbose_name='Етапи роботи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Сторінка послуги',
                'verbose_name_plural': 'Сторінки послуг',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('icon_name', models.CharField(blank=True, max_length=60, verbose_name='Іконка (CSS-клас)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.servicepage', verbose_name='Послуга')),
            ],
            options={
                'verbose_name': 'Перевага',
                'verbose_name_plural': 'Переваги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Питання')),
                ('answer', models.TextField(verbose_name='Відповідь')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='services.servicepage', verbose_name='Послуга')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order'],
            },
        ),
    ]
