# Generated by Django 4.2.30 on 2026-04-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_data_fixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(blank=True, verbose_name='Відповідь (RU)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(blank=True, max_length=300, verbose_name='Питання (RU)'),
        ),
        migrations.AddField(
            model_name='feature',
            name='text_ru',
            field=models.TextField(blank=True, verbose_name='Текст (RU)'),
        ),
        migrations.AddField(
            model_name='feature',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок (RU)'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='body_intro_ru',
            field=models.TextField(blank=True, verbose_name='Вступний текст (RU)'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='h1_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='H1 (RU)'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='hero_subtitle_ru',
            field=models.TextField(blank=True, verbose_name='Підзаголовок hero (RU)'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='meta_description_ru',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta description (RU)'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=70, verbose_name='Meta title (RU)'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='process_steps_ru',
            field=models.JSONField(blank=True, default=list, help_text='JSON: [{"title": "...", "text": "..."}]', verbose_name='Етапи роботи (RU)'),
        ),
    ]
