# Generated by Django 4.2.30 on 2026-04-11 13:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='DOuIT', max_length=100, verbose_name='Назва сайту')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram URL')),
                ('whatsapp_url', models.URLField(blank=True, verbose_name='WhatsApp URL')),
                ('slots_available', models.PositiveSmallIntegerField(default=3, verbose_name='Вільних слотів')),
                ('og_image', models.ImageField(blank=True, upload_to='og/', verbose_name='OG-зображення')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name="Ім'я")),
                ('company', models.CharField(blank=True, max_length=120, verbose_name='Компанія')),
                ('text', models.TextField(verbose_name='Відгук')),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('url', models.URLField(blank=True, verbose_name='URL проєкту')),
                ('screenshot', models.ImageField(upload_to='portfolio/', verbose_name='Скріншот')),
                ('description', models.TextField(max_length=300, verbose_name='Опис')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_items', to='services.servicepage', verbose_name='Тип послуги')),
            ],
            options={
                'verbose_name': 'Робота в портфоліо',
                'verbose_name_plural': 'Портфоліо',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
