# Generated by Django 4.2.30 on 2026-04-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='slots_available',
        ),
    ]
