# Generated by Django 4.2.30 on 2026-04-12 12:33

from django.db import migrations


def set_contacts(apps, schema_editor):
    SiteSettings = apps.get_model("core", "SiteSettings")
    SiteSettings.objects.update_or_create(
        pk=1,
        defaults={
            "phone": "+38(068)611-91-50",
            "email": "douit.main@gmail.com",
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_sitesettings_slots_available"),
    ]

    operations = [
        migrations.RunPython(set_contacts, migrations.RunPython.noop),
    ]
