# Generated by Django 4.2.30 on 2026-04-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_data_phone_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='description_ru',
            field=models.TextField(blank=True, max_length=300, verbose_name='Опис (RU)'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Назва (RU)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='company_ru',
            field=models.CharField(blank=True, max_length=120, verbose_name='Компанія (RU)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name_ru',
            field=models.CharField(blank=True, max_length=120, verbose_name="Ім'я (RU)"),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='text_ru',
            field=models.TextField(blank=True, verbose_name='Відгук (RU)'),
        ),
    ]
