# Generated by Django 4.2.30 on 2026-04-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name="Ім'я")),
                ('contact', models.CharField(max_length=200, verbose_name='Телефон або email')),
                ('project_type', models.CharField(choices=[('ecommerce', 'Інтернет-магазин'), ('landing', 'Лендінг'), ('corporate', 'Корпоративний сайт'), ('other', 'Інше')], default='other', max_length=20, verbose_name='Тип проєкту')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('status', models.CharField(choices=[('new', 'Новий'), ('in_progress', 'В роботі'), ('done', 'Завершено'), ('spam', 'Спам')], default='new', max_length=20, verbose_name='Статус')),
                ('utm_source', models.CharField(blank=True, max_length=200, verbose_name='UTM source')),
                ('utm_medium', models.CharField(blank=True, max_length=200, verbose_name='UTM medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=200, verbose_name='UTM campaign')),
                ('source_url', models.URLField(blank=True, verbose_name='URL джерела')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
