# Generated by Django 4.2.30 on 2026-04-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='quiz_budget',
            field=models.CharField(blank=True, max_length=30, verbose_name='Бюджет (квіз)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='quiz_deadline',
            field=models.CharField(blank=True, max_length=30, verbose_name='Терміни (квіз)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='quiz_features',
            field=models.TextField(blank=True, verbose_name='Функціонал (квіз)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='quiz_pages',
            field=models.CharField(blank=True, max_length=20, verbose_name='Кількість сторінок (квіз)'),
        ),
    ]
