# Generated by Django 4.2.30 on 2026-04-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_add_quiz_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='contact',
            field=models.CharField(max_length=200, verbose_name='Телефон'),
        ),
    ]
