# Generated by Django 4.2.30 on 2026-04-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='project_type',
            field=models.CharField(blank=True, choices=[('ecommerce', 'Інтернет-магазин'), ('landing', 'Лендінг'), ('corporate', 'Корпоративний сайт'), ('other', 'Інше')], default='other', max_length=20, verbose_name='Тип проєкту'),
        ),
    ]
